// 2026-07-14 — Added NODE_SIZEOF, NODE_CAST, NODE_DROP_CALL emission.
//   Auto-includes <stdlib.h> and <stddef.h> in emitted output.
// 2026-07-13 — C code generator for C².
//   Walks the AST and emits standard C23 code.
//   Strips contracts, converts borrow/own to standard pointers,
//   converts when to if, and emits derivation blocks as comments.

#include "codegen.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <inttypes.h>

// ── Forward declarations ────────────────────────────────────────────────

static void emit_node(Codegen* cg, AstNode* node);
static void emit_indent(Codegen* cg);
static void cg_putc(Codegen* cg, char c);
static void cg_puts(Codegen* cg, const char* s);
static void cg_printf(Codegen* cg, const char* fmt, ...);
static void cg_ensure_cap(Codegen* cg, size_t needed);

// ── Init / free ─────────────────────────────────────────────────────────

void codegen_init(Codegen* cg, ErrorList* errors) {
    cg->output = NULL;
    cg->output_len = 0;
    cg->output_cap = 0;
    cg->indent_level = 0;
    cg->errors = errors;
}

void codegen_free(Codegen* cg) {
    free(cg->output);
    cg->output = NULL;
    cg->output_len = 0;
    cg->output_cap = 0;
}

// ── Output generation ───────────────────────────────────────────────────

const char* codegen_generate(Codegen* cg, AstNode* root) {
    if (!root) return "";

    // Reserve initial capacity
    cg_ensure_cap(cg, 4096);
    cg->output_len = 0;
    cg->output[0] = '\0';

    // Emit header comment and required includes
    cg_puts(cg, "// Generated by C² (Contract Enforced C) transpiler\n");
    cg_puts(cg, "// Standard C23 — safe to compile with gcc -std=c23\n");
    cg_puts(cg, "#include <stdint.h>\n");
    cg_puts(cg, "#include <stdlib.h>\n");
    cg_puts(cg, "#include <stddef.h>\n\n");

    // Emit translation unit children
    for (size_t i = 0; i < root->child_count; i++) {
        emit_node(cg, root->children[i]);
    }

    cg_putc(cg, '\n');
    return cg->output;
}

int codegen_write_file(Codegen* cg, const char* path) {
    FILE* f = fopen(path, "w");
    if (!f) return -1;
    if (cg->output) {
        fwrite(cg->output, 1, cg->output_len, f);
    }
    fclose(f);
    return 0;
}

// ── Node emitter ────────────────────────────────────────────────────────

static void emit_node(Codegen* cg, AstNode* node) {
    if (!node) return;

    switch (node->kind) {
        case NODE_TRANSLATION_UNIT:
            for (size_t i = 0; i < node->child_count; i++) {
                emit_node(cg, node->children[i]);
            }
            break;

        case NODE_FUNCTION: {
            // Skip main() in verify/derive modes to avoid linker conflict
            if (cg->skip_main && node->token.len == 4 &&
                memcmp(node->token.text, "main", 4) == 0) {
                break;
            }

            // Emit derivation examples as comments
            for (size_t i = 0; i < node->child_count; i++) {
                if (node->children[i]->kind == NODE_DERIVATION) {
                    emit_node(cg, node->children[i]);
                }
            }

            // Return type (first child, always present)
            if (node->child_count > 0) {
                emit_node(cg, node->children[0]);
                cg_putc(cg, ' ');
            }

            // Function name
            cg_printf(cg, "%.*s(", (int)node->token.len, node->token.text);

            // Parameters
            for (size_t i = 0; i < node->child_count; i++) {
                AstNode* child = node->children[i];
                if (child->kind == NODE_PARAM_LIST) {
                    for (size_t j = 0; j < child->child_count; j++) {
                        if (j > 0) cg_puts(cg, ", ");
                        emit_node(cg, child->children[j]);
                    }
                }
            }
            cg_puts(cg, ")");

            // Body
            for (size_t i = 0; i < node->child_count; i++) {
                if (node->children[i]->kind == NODE_BLOCK) {
                    cg_putc(cg, ' ');
                    emit_node(cg, node->children[i]);
                    break;
                }
            }

            // Derivation block after body (emitted as comment already done above)
            // Now emit the derivation block comment again if present
            cg_putc(cg, '\n');
            break;
        }

        case NODE_PARAM_LIST:
            for (size_t i = 0; i < node->child_count; i++) {
                if (i > 0) cg_puts(cg, ", ");
                emit_node(cg, node->children[i]);
            }
            break;

        case NODE_DECL: {
            // Check for borrow/own qualifiers before emitting the type
            int is_borrow = 0;
            int is_own = 0;
            for (size_t ci = 1; ci < node->child_count; ci++) {
                if (node->children[ci]->kind == NODE_BORROW_PARAM) is_borrow = 1;
                if (node->children[ci]->kind == NODE_OWN_PARAM) is_own = 1;
            }

            if (node->child_count > 0) {
                AstNode* type_node = node->children[0];
                // Inline struct/union/enum definition: emit body without trailing ;
                if (type_node->kind == NODE_STRUCT_DECL ||
                    type_node->kind == NODE_UNION_DECL ||
                    type_node->kind == NODE_ENUM_DECL) {
                    const char* kw = type_node->kind == NODE_STRUCT_DECL ? "struct "
                                   : type_node->kind == NODE_UNION_DECL  ? "union "
                                   :                                      "enum ";
                    cg_puts(cg, kw);
                    size_t ci = 0;
                    if (ci < type_node->child_count && type_node->children[ci]->kind == NODE_VARIABLE) {
                        emit_node(cg, type_node->children[ci]);
                        cg_putc(cg, ' ');
                        ci++;
                    }
                    int has_body = 0;
                    for (size_t j = ci; j < type_node->child_count; j++) {
                        if (type_node->children[j]->kind == NODE_STRUCT_FIELD) { has_body = 1; break; }
                    }
                    if (has_body) {
                        cg_puts(cg, "{\n");
                        cg->indent_level++;
                        for (size_t j = ci; j < type_node->child_count; j++) {
                            AstNode* field = type_node->children[j];
                            if (field->kind == NODE_STRUCT_FIELD) {
                                emit_indent(cg);
                                if (field->child_count > 0) emit_node(cg, field->children[0]);
                                cg_putc(cg, ' ');
                                cg_printf(cg, "%.*s", (int)field->token.len, field->token.text);
                                for (size_t k = 1; k < field->child_count; k++) {
                                    if (field->children[k]->kind == NODE_ARRAY_SUB) {
                                        cg_putc(cg, '[');
                                        if (field->children[k]->child_count > 0)
                                            emit_node(cg, field->children[k]->children[0]);
                                        cg_putc(cg, ']');
                                    } else {
                                        cg_puts(cg, " = ");
                                        emit_node(cg, field->children[k]);
                                    }
                                }
                                cg_puts(cg, ";\n");
                            }
                        }
                        cg->indent_level--;
                        emit_indent(cg);
                        cg_putc(cg, '}');
                    }
                    cg_putc(cg, ' ');
                    cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
                } else {
                    // For pointer types with borrow/own: emit const qualifier correctly
                    if ((is_borrow || is_own) && node->children[0]->kind == NODE_VARIABLE) {
                        AstNode* vt = node->children[0];
                        // Check if this is a pointer type (has star marker)
                        int has_star = 0;
                        for (size_t ci = 0; ci < vt->child_count; ci++) {
                            if (vt->children[ci]->kind == NODE_VARIABLE &&
                                vt->children[ci]->token.kind == TOK_STAR) {
                                has_star = 1;
                                break;
                            }
                        }
                        if (has_star) {
                            // Emit: [const] type * restrict name
                            if (is_borrow) cg_puts(cg, "const ");
                            emit_node(cg, vt);
                            // Emit pointer stars (count them first to add restrict)
                            int pdepth = 0;
                            for (size_t ci = 0; ci < vt->child_count; ci++) {
                                AstNode* pc = vt->children[ci];
                                if (pc->kind == NODE_VARIABLE && pc->token.kind == TOK_STAR)
                                    pdepth = pc->flags;
                            }
                            if (pdepth > 0) {
                                for (int pi = 1; pi < pdepth; pi++) cg_putc(cg, '*');
                                cg_puts(cg, "* restrict ");
                            } else {
                                cg_putc(cg, ' ');
                            }
                            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
                        } else {
                            emit_node(cg, node->children[0]);
                            cg_putc(cg, ' ');
                            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
                        }
                    } else {
                        emit_node(cg, node->children[0]);
                        // Emit pointer stars from type node's pointer marker
                        if (node->children[0]->kind == NODE_VARIABLE) {
                            for (size_t ci = 0; ci < node->children[0]->child_count; ci++) {
                                AstNode* pc = node->children[0]->children[ci];
                                if (pc->kind == NODE_VARIABLE && pc->token.kind == TOK_STAR) {
                                    for (int pd = 0; pd < pc->flags; pd++) cg_putc(cg, '*');
                                }
                            }
                        }
                        cg_putc(cg, ' ');
                        cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
                    }
                }
            }
            for (size_t i = 1; i < node->child_count; i++) {
                AstNode* child = node->children[i];
                if (child->kind == NODE_BORROW_PARAM || child->kind == NODE_OWN_PARAM) {
                    // Already handled above — skip
                } else if (child->kind == NODE_ARRAY_SUB) {
                    cg_putc(cg, '[');
                    if (child->child_count > 0) emit_node(cg, child->children[0]);
                    cg_putc(cg, ']');
                } else {
                    cg_puts(cg, " = ");
                    emit_node(cg, child);
                }
            }
            break;
        }

        case NODE_BLOCK: {
            cg_putc(cg, '{');
            cg->indent_level++;
            if (node->child_count > 0) cg_putc(cg, '\n');
            for (size_t i = 0; i < node->child_count; i++) {
                emit_node(cg, node->children[i]);
            }
            cg->indent_level--;
            if (node->child_count > 0) {
                emit_indent(cg);
            }
            cg_putc(cg, '}');
            break;
        }

        case NODE_WHEN: {
            // when condition -> statement;  →  if (condition) { statement; }
            emit_indent(cg);
            cg_puts(cg, "if (");
            // Children: [0] = condition, [1] = statement
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 1) {
                // Check if the statement is a block (already has braces)
                if (node->children[1]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                }
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "}");
            // If VRP has proven the condition is always true, emit
            // __builtin_unreachable() after the block as an optimization hint.
            if (node->child_count > 0) {
                AstNode* cond = node->children[0];
                if (cond->range.has_range && cond->range.lo > 0) {
                    cg_puts(cg, " __builtin_unreachable();\n");
                } else {
                    cg_putc(cg, '\n');
                }
            } else {
                cg_putc(cg, '\n');
            }
            break;
        }

        case NODE_IF: {
            emit_indent(cg);
            cg_puts(cg, "if (");
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 1) {
                if (node->children[1]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                }
            }
            cg->indent_level--;
            cg_putc(cg, '\n');
            emit_indent(cg);
            cg_puts(cg, "}\n");

            // Check for else
            for (size_t i = 0; i < node->child_count; i++) {
                if (node->children[i]->kind == NODE_ELSE) {
                    cg_puts(cg, " else {");
                    cg->indent_level++;
                    AstNode* else_node = node->children[i];
                    if (else_node->child_count > 0) {
                        if (else_node->children[0]->kind == NODE_BLOCK) {
                            cg->indent_level--;
                            cg_putc(cg, '\n');
                            emit_node(cg, else_node->children[0]);
                            cg->indent_level++;
                        } else {
                            cg_putc(cg, '\n');
                            emit_node(cg, else_node->children[0]);
                        }
                    }
                    cg->indent_level--;
                    emit_indent(cg);
                    cg_puts(cg, "}");
                }
            }
            break;
        }

        case NODE_WHILE: {
            emit_indent(cg);
            cg_puts(cg, "while (");
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 1) {
                if (node->children[1]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                }
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "}");
            cg_putc(cg, '\n');
            break;
        }

        case NODE_DO_WHILE: {
            emit_indent(cg);
            cg_puts(cg, "do {");
            cg->indent_level++;
            if (node->child_count > 0) {
                if (node->children[0]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[0]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[0]);
                }
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "} while (");
            if (node->child_count > 1) emit_node(cg, node->children[1]);
            cg_puts(cg, ");\n");
            break;
        }

        case NODE_FOR: {
            emit_indent(cg);
            cg_puts(cg, "for (");
            // Children: [0] = init, [1] = cond, [2] = inc, [3] = body
            if (node->child_count > 0 && node->children[0]) emit_node(cg, node->children[0]);
            cg_puts(cg, "; ");
            if (node->child_count > 1 && node->children[1]) emit_node(cg, node->children[1]);
            cg_puts(cg, "; ");
            if (node->child_count > 2 && node->children[2]) emit_node(cg, node->children[2]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 3 && node->children[3]) {
                cg_putc(cg, '\n');
                if (node->children[3]->kind == NODE_BLOCK) {
                    // For blocks, emit contents directly (no extra braces)
                    for (size_t bi = 0; bi < node->children[3]->child_count; bi++) {
                        emit_node(cg, node->children[3]->children[bi]);
                    }
                } else {
                    emit_indent(cg);
                    emit_node(cg, node->children[3]);
                    cg_putc(cg, ';');
                    cg_putc(cg, '\n');
                }
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "}");
            cg_putc(cg, '\n');
            break;
        }

        case NODE_EXPR_STMT: {
            emit_indent(cg);
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ";\n");
            break;
        }

        case NODE_RETURN: {
            emit_indent(cg);
            cg_puts(cg, "return");
            if (node->child_count > 0 && node->children[0]) {
                cg_putc(cg, ' ');
                emit_node(cg, node->children[0]);
            }
            cg_puts(cg, ";\n");
            break;
        }

        case NODE_BREAK: {
            emit_indent(cg);
            cg_puts(cg, "break;\n");
            break;
        }

        case NODE_CONTINUE: {
            emit_indent(cg);
            cg_puts(cg, "continue;\n");
            break;
        }

        case NODE_SWITCH: {
            emit_indent(cg);
            cg_puts(cg, "switch (");
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            cg_putc(cg, '\n');
            for (size_t i = 1; i < node->child_count; i++) {
                emit_node(cg, node->children[i]);
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "}\n");
            break;
        }

        case NODE_CASE: {
            emit_indent(cg);
            cg_puts(cg, "case ");
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ":\n");
            break;
        }

        case NODE_DEFAULT: {
            emit_indent(cg);
            cg_puts(cg, "default:\n");
            break;
        }

        case NODE_DERIVATION: {
            // Emit derivation examples as comments
            for (size_t i = 0; i < node->child_count; i++) {
                AstNode* example = node->children[i];
                if (example->kind != NODE_DERIV_EXAMPLE) continue;

                // Determine output index (account for optional tolerance wrapper)
                size_t last = example->child_count;
                size_t output_idx = last > 0 ? last - 1 : 0;
                AstNode* tol = NULL;
                if (last > 0 && example->children[last - 1]->kind == NODE_DERIV_TOLERANCE) {
                    output_idx = last > 1 ? last - 2 : 0;
                    if (example->children[last - 1]->child_count > 0)
                        tol = example->children[last - 1]->children[0];
                }

                cg_puts(cg, "// Derivation example: ");
                for (size_t j = 0; j < output_idx; j++) {
                    if (j > 0) cg_puts(cg, ", ");
                    AstNode* in = example->children[j];
                    if (in->kind == NODE_LITERAL_INT) {
                        cg_printf(cg, "%" PRId64, in->token.value.i64);
                    } else if (in->kind == NODE_LITERAL_FLOAT) {
                        cg_printf(cg, "%g", in->token.value.f64);
                    } else {
                        cg_puts(cg, "expr");
                    }
                }
                cg_puts(cg, " -> ");
                if (output_idx < last) {
                    AstNode* out = example->children[output_idx];
                    if (out->kind == NODE_LITERAL_INT) {
                        cg_printf(cg, "%" PRId64, out->token.value.i64);
                    } else if (out->kind == NODE_LITERAL_FLOAT) {
                        cg_printf(cg, "%g", out->token.value.f64);
                    } else {
                        cg_puts(cg, "expr");
                    }
                }
                if (tol) {
                    cg_puts(cg, " [tol=");
                    if (tol->kind == NODE_LITERAL_FLOAT) {
                        cg_printf(cg, "%g", tol->token.value.f64);
                    } else if (tol->kind == NODE_LITERAL_INT) {
                        cg_printf(cg, "%" PRId64, tol->token.value.i64);
                    } else {
                        cg_puts(cg, "expr");
                    }
                    cg_putc(cg, ']');
                }
                cg_putc(cg, '\n');
            }
            break;
        }

        case NODE_BINARY_OP: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_printf(cg, " %s ", token_kind_name(node->token.kind));
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_UNARY_OP: {
            const char* op = token_kind_name(node->token.kind);
            if (node->token.kind == TOK_STAR) {
                cg_putc(cg, '*');
            } else if (node->token.kind == TOK_BIT_AND) {
                cg_putc(cg, '&');
            } else if (node->token.kind == TOK_INC || node->token.kind == TOK_DEC) {
                // Postfix: emit operand first
                if (node->child_count > 0) emit_node(cg, node->children[0]);
                cg_puts(cg, op);
                return;
            } else {
                cg_puts(cg, op);
            }
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            break;
        }

        case NODE_TERNARY: {
            if (node->child_count >= 3) {
                emit_node(cg, node->children[0]);
                cg_puts(cg, " ? ");
                emit_node(cg, node->children[1]);
                cg_puts(cg, " : ");
                emit_node(cg, node->children[2]);
            }
            break;
        }

        case NODE_ASSIGN: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_printf(cg, " %s ", token_kind_name(node->token.kind));
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_CALL: {
            if (node->child_count > 0) {
                emit_node(cg, node->children[0]);
                cg_puts(cg, "(");
                for (size_t i = 1; i < node->child_count; i++) {
                    if (i > 1) cg_puts(cg, ", ");
                    emit_node(cg, node->children[i]);
                }
                cg_puts(cg, ")");
            }
            break;
        }

        case NODE_INDEX: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_putc(cg, '[');
                emit_node(cg, node->children[1]);
                cg_putc(cg, ']');
            }
            break;
        }

        case NODE_MEMBER: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_putc(cg, '.');
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_DEREF: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_puts(cg, "->");
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_LITERAL_INT: {
            cg_printf(cg, "%" PRId64, node->token.value.i64);
            break;
        }

        case NODE_LITERAL_FLOAT: {
            cg_printf(cg, "%g", node->token.value.f64);
            break;
        }

        case NODE_LITERAL_STR: {
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            break;
        }

        case NODE_LITERAL_CHAR: {
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            break;
        }

        case NODE_VARIABLE: {
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            // struct/union/enum type: emit `struct Foo` not just `struct`
            if ((node->token.kind == TOK_STRUCT || node->token.kind == TOK_UNION || node->token.kind == TOK_ENUM)
                && node->child_count > 0) {
                cg_putc(cg, ' ');
                emit_node(cg, node->children[0]);
            }
            break;
        }

        case NODE_STRUCT_DECL: {
            emit_indent(cg);
            cg_puts(cg, "struct ");
            // First child is optional name (NODE_VARIABLE)
            size_t ci = 0;
            if (ci < node->child_count && node->children[ci]->kind == NODE_VARIABLE) {
                emit_node(cg, node->children[ci]);
                cg_putc(cg, ' ');
                ci++;
            }
            // Check if forward declaration (no field children)
            int has_fields = 0;
            for (size_t j = ci; j < node->child_count; j++) {
                if (node->children[j]->kind == NODE_STRUCT_FIELD) { has_fields = 1; break; }
            }
            if (has_fields) {
                cg_puts(cg, "{\n");
                cg->indent_level++;
                for (size_t j = ci; j < node->child_count; j++) {
                    AstNode* field = node->children[j];
                    if (field->kind == NODE_STRUCT_FIELD) {
                        emit_indent(cg);
                        if (field->child_count > 0) emit_node(cg, field->children[0]);
                        cg_putc(cg, ' ');
                        cg_printf(cg, "%.*s", (int)field->token.len, field->token.text);
                        // Array subscript?
                        for (size_t k = 1; k < field->child_count; k++) {
                            cg_putc(cg, '[');
                            emit_node(cg, field->children[k]);
                            cg_putc(cg, ']');
                        }
                        cg_puts(cg, ";\n");
                    }
                }
                cg->indent_level--;
                emit_indent(cg);
                cg_putc(cg, '}');
            }
            cg_puts(cg, ";\n");
            break;
        }

        case NODE_UNION_DECL: {
            emit_indent(cg);
            cg_puts(cg, "union ");
            size_t ci = 0;
            if (ci < node->child_count && node->children[ci]->kind == NODE_VARIABLE) {
                emit_node(cg, node->children[ci]);
                cg_putc(cg, ' ');
                ci++;
            }
            int has_fields = 0;
            for (size_t j = ci; j < node->child_count; j++) {
                if (node->children[j]->kind == NODE_STRUCT_FIELD) { has_fields = 1; break; }
            }
            if (has_fields) {
                cg_puts(cg, "{\n");
                cg->indent_level++;
                for (size_t j = ci; j < node->child_count; j++) {
                    AstNode* field = node->children[j];
                    if (field->kind == NODE_STRUCT_FIELD) {
                        emit_indent(cg);
                        if (field->child_count > 0) emit_node(cg, field->children[0]);
                        cg_putc(cg, ' ');
                        cg_printf(cg, "%.*s", (int)field->token.len, field->token.text);
                        for (size_t k = 1; k < field->child_count; k++) {
                            cg_putc(cg, '[');
                            emit_node(cg, field->children[k]);
                            cg_putc(cg, ']');
                        }
                        cg_puts(cg, ";\n");
                    }
                }
                cg->indent_level--;
                emit_indent(cg);
                cg_putc(cg, '}');
            }
            cg_puts(cg, ";\n");
            break;
        }

        case NODE_ENUM_DECL: {
            emit_indent(cg);
            cg_puts(cg, "enum ");
            size_t ci = 0;
            if (ci < node->child_count && node->children[ci]->kind == NODE_VARIABLE) {
                emit_node(cg, node->children[ci]);
                cg_putc(cg, ' ');
                ci++;
            }
            int has_enumerators = 0;
            for (size_t j = ci; j < node->child_count; j++) {
                if (node->children[j]->kind == NODE_STRUCT_FIELD) { has_enumerators = 1; break; }
            }
            if (has_enumerators) {
                cg_puts(cg, "{\n");
                cg->indent_level++;
                for (size_t j = ci; j < node->child_count; j++) {
                    AstNode* enumerator = node->children[j];
                    if (enumerator->kind == NODE_STRUCT_FIELD) {
                        emit_indent(cg);
                        cg_printf(cg, "%.*s", (int)enumerator->token.len, enumerator->token.text);
                        if (enumerator->child_count > 0) {
                            cg_puts(cg, " = ");
                            emit_node(cg, enumerator->children[0]);
                        }
                        if (j + 1 < node->child_count) cg_putc(cg, ',');
                        cg_putc(cg, '\n');
                    }
                }
                cg->indent_level--;
                emit_indent(cg);
                cg_putc(cg, '}');
            }
            cg_puts(cg, ";\n");
            break;
        }

        case NODE_ARRAY_SUB: {
            cg_putc(cg, '[');
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_putc(cg, ']');
            break;
        }

        case NODE_TYPEDEF: {
            emit_indent(cg);
            cg_puts(cg, "typedef ");
            // Children: [0] = type (may be struct/union/enum decl), [1] = name
            if (node->child_count > 0) {
                AstNode* type_node = node->children[0];
                // For typedef struct/union/enum { ... } Name; emit without extra ;
                if (type_node->kind == NODE_STRUCT_DECL ||
                    type_node->kind == NODE_UNION_DECL ||
                    type_node->kind == NODE_ENUM_DECL) {
                    // Emit struct/union/enum name { ... }
                    const char* kw = type_node->kind == NODE_STRUCT_DECL ? "struct "
                                   : type_node->kind == NODE_UNION_DECL  ? "union "
                                   :                                      "enum ";
                    cg_puts(cg, kw);
                    size_t ci = 0;
                    if (ci < type_node->child_count && type_node->children[ci]->kind == NODE_VARIABLE) {
                        emit_node(cg, type_node->children[ci]);
                        cg_putc(cg, ' ');
                        ci++;
                    }
                    int has_body = 0;
                    for (size_t j = ci; j < type_node->child_count; j++) {
                        if (type_node->children[j]->kind == NODE_STRUCT_FIELD) { has_body = 1; break; }
                    }
                    if (has_body) {
                        cg_puts(cg, "{\n");
                        cg->indent_level++;
                        for (size_t j = ci; j < type_node->child_count; j++) {
                            AstNode* field = type_node->children[j];
                            if (field->kind == NODE_STRUCT_FIELD) {
                                emit_indent(cg);
                                if (field->child_count > 0) emit_node(cg, field->children[0]);
                                cg_putc(cg, ' ');
                                const char* fname = field->token.text;
                                size_t flen = field->token.len;
                                cg_printf(cg, "%.*s", (int)flen, fname);
                                for (size_t k = 1; k < field->child_count; k++) {
                                    if (field->children[k]->kind == NODE_ARRAY_SUB) {
                                        cg_putc(cg, '[');
                                        if (field->children[k]->child_count > 0)
                                            emit_node(cg, field->children[k]->children[0]);
                                        cg_putc(cg, ']');
                                    } else {
                                        cg_puts(cg, " = ");
                                        emit_node(cg, field->children[k]);
                                    }
                                }
                                cg_puts(cg, ";\n");
                            }
                        }
                        cg->indent_level--;
                        emit_indent(cg);
                        cg_putc(cg, '}');
                    }
                    cg_putc(cg, ' ');
                    if (node->child_count > 1) emit_node(cg, node->children[1]);
                    cg_puts(cg, ";\n");
                } else {
                    emit_node(cg, type_node);
                    cg_putc(cg, ' ');
                    if (node->child_count > 1) emit_node(cg, node->children[1]);
                    cg_puts(cg, ";\n");
                }
            }
            break;
        }

        case NODE_PP_INCLUDE: {
            emit_indent(cg);
            cg_printf(cg, "%.*s\n", (int)node->token.len, node->token.text);
            break;
        }

        case NODE_CAST: {
            // (type)expr
            if (node->child_count >= 2) {
                cg_putc(cg, '(');
                emit_node(cg, node->children[0]);
                cg_putc(cg, ')');
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_SIZEOF: {
            // sizeof expr  or  sizeof(expr)
            cg_puts(cg, "sizeof(");
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_putc(cg, ')');
            break;
        }

        case NODE_DROP_CALL: {
            // free(varname); varname = NULL;
            emit_indent(cg);
            cg_puts(cg, "free(");
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            cg_puts(cg, ");\n");
            emit_indent(cg);
            cg_printf(cg, "%.*s = NULL;\n", (int)node->token.len, node->token.text);
            break;
        }

        default:
            emit_indent(cg);
            cg_printf(cg, "/* unknown node kind %d */\n", node->kind);
            break;
    }
}

// ── Output buffer helpers ───────────────────────────────────────────────

static void emit_indent(Codegen* cg) {
    for (int i = 0; i < cg->indent_level; i++) {
        cg_putc(cg, ' ');
        cg_putc(cg, ' ');
    }
}

static void cg_ensure_cap(Codegen* cg, size_t needed) {
    if (cg->output_cap == 0) {
        cg->output_cap = needed;
        cg->output = (char*)malloc(cg->output_cap);
        cg->output[0] = '\0';
    } else if (cg->output_len + needed >= cg->output_cap) {
        cg->output_cap *= 2;
        cg->output = (char*)realloc(cg->output, cg->output_cap);
    }
}

static void cg_putc(Codegen* cg, char c) {
    cg_ensure_cap(cg, 2);
    cg->output[cg->output_len++] = c;
    cg->output[cg->output_len] = '\0';
}

static void cg_puts(Codegen* cg, const char* s) {
    size_t len = strlen(s);
    cg_ensure_cap(cg, len + 1);
    memcpy(cg->output + cg->output_len, s, len);
    cg->output_len += len;
    cg->output[cg->output_len] = '\0';
}

static void cg_printf(Codegen* cg, const char* fmt, ...) {
    va_list args;
    va_start(args, fmt);
    int needed = vsnprintf(NULL, 0, fmt, args);
    va_end(args);
    if (needed < 0) return;

    cg_ensure_cap(cg, (size_t)needed + 1);
    va_start(args, fmt);
    vsnprintf(cg->output + cg->output_len, (size_t)needed + 1, fmt, args);
    va_end(args);
    cg->output_len += (size_t)needed;
}
