// 2026-07-13 — C code generator for C².
//   Walks the AST and emits standard C23 code.
//   Strips contracts, converts borrow/own to standard pointers,
//   converts when to if, and emits derivation blocks as comments.

#include "codegen.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <inttypes.h>

// ── Forward declarations ────────────────────────────────────────────────

static void emit_node(Codegen* cg, AstNode* node);
static void emit_indent(Codegen* cg);
static void cg_putc(Codegen* cg, char c);
static void cg_puts(Codegen* cg, const char* s);
static void cg_printf(Codegen* cg, const char* fmt, ...);
static void cg_ensure_cap(Codegen* cg, size_t needed);

// ── Init / free ─────────────────────────────────────────────────────────

void codegen_init(Codegen* cg, ErrorList* errors) {
    cg->output = NULL;
    cg->output_len = 0;
    cg->output_cap = 0;
    cg->indent_level = 0;
    cg->errors = errors;
}

void codegen_free(Codegen* cg) {
    free(cg->output);
    cg->output = NULL;
    cg->output_len = 0;
    cg->output_cap = 0;
}

// ── Output generation ───────────────────────────────────────────────────

const char* codegen_generate(Codegen* cg, AstNode* root) {
    if (!root) return "";

    // Reserve initial capacity
    cg_ensure_cap(cg, 4096);
    cg->output_len = 0;
    cg->output[0] = '\0';

    // Emit header comment
    cg_puts(cg, "// Generated by C² (Contract Enforced C) transpiler\n");
    cg_puts(cg, "// Standard C23 — safe to compile with gcc -std=c23\n\n");

    // Emit translation unit children
    for (size_t i = 0; i < root->child_count; i++) {
        emit_node(cg, root->children[i]);
    }

    cg_putc(cg, '\n');
    return cg->output;
}

int codegen_write_file(Codegen* cg, const char* path) {
    FILE* f = fopen(path, "w");
    if (!f) return -1;
    if (cg->output) {
        fwrite(cg->output, 1, cg->output_len, f);
    }
    fclose(f);
    return 0;
}

// ── Node emitter ────────────────────────────────────────────────────────

static void emit_node(Codegen* cg, AstNode* node) {
    if (!node) return;

    switch (node->kind) {
        case NODE_TRANSLATION_UNIT:
            for (size_t i = 0; i < node->child_count; i++) {
                emit_node(cg, node->children[i]);
            }
            break;

        case NODE_FUNCTION: {
            // Emit derivation examples as comments
            for (size_t i = 0; i < node->child_count; i++) {
                if (node->children[i]->kind == NODE_DERIVATION) {
                    emit_node(cg, node->children[i]);
                }
            }

            // Return type (first child, always present)
            if (node->child_count > 0) {
                emit_node(cg, node->children[0]);
                cg_putc(cg, ' ');
            }

            // Function name
            cg_printf(cg, "%.*s(", (int)node->token.len, node->token.text);

            // Parameters
            for (size_t i = 0; i < node->child_count; i++) {
                AstNode* child = node->children[i];
                if (child->kind == NODE_PARAM_LIST) {
                    for (size_t j = 0; j < child->child_count; j++) {
                        if (j > 0) cg_puts(cg, ", ");
                        emit_node(cg, child->children[j]);
                    }
                }
            }
            cg_puts(cg, ")");

            // Body
            for (size_t i = 0; i < node->child_count; i++) {
                if (node->children[i]->kind == NODE_BLOCK) {
                    cg_putc(cg, ' ');
                    emit_node(cg, node->children[i]);
                    break;
                }
            }

            // Derivation block after body (emitted as comment already done above)
            // Now emit the derivation block comment again if present
            cg_putc(cg, '\n');
            break;
        }

        case NODE_PARAM_LIST:
            for (size_t i = 0; i < node->child_count; i++) {
                if (i > 0) cg_puts(cg, ", ");
                emit_node(cg, node->children[i]);
            }
            break;

        case NODE_DECL: {
            // Type (first child)
            if (node->child_count > 0) {
                emit_node(cg, node->children[0]);
                cg_putc(cg, ' ');
            }
            // Variable/param name
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            // Children after type: array size, initializer, borrow/own
            for (size_t i = 1; i < node->child_count; i++) {
                AstNode* child = node->children[i];
                if (child->kind == NODE_BORROW_PARAM) {
                    cg_puts(cg, " const*");
                } else if (child->kind == NODE_OWN_PARAM) {
                    cg_puts(cg, "*");
                } else if (child->kind == NODE_LITERAL_INT || child->kind == NODE_VARIABLE ||
                           child->kind == NODE_BINARY_OP) {
                    cg_putc(cg, '[');
                    emit_node(cg, child);
                    cg_putc(cg, ']');
                } else {
                    cg_puts(cg, " = ");
                    emit_node(cg, child);
                }
            }
            break;
        }

        case NODE_BLOCK: {
            cg_putc(cg, '{');
            cg->indent_level++;
            if (node->child_count > 0) cg_putc(cg, '\n');
            for (size_t i = 0; i < node->child_count; i++) {
                emit_node(cg, node->children[i]);
            }
            cg->indent_level--;
            if (node->child_count > 0) {
                emit_indent(cg);
            }
            cg_putc(cg, '}');
            break;
        }

        case NODE_WHEN: {
            // when condition -> statement;  →  if (condition) { statement; }
            emit_indent(cg);
            cg_puts(cg, "if (");
            // Children: [0] = condition, [1] = statement
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 1) {
                // Check if the statement is a block (already has braces)
                if (node->children[1]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                }
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "}\n");
            break;
        }

        case NODE_IF: {
            emit_indent(cg);
            cg_puts(cg, "if (");
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 1) {
                if (node->children[1]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                }
            }
            cg->indent_level--;
            cg_putc(cg, '\n');
            emit_indent(cg);
            cg_puts(cg, "}\n");

            // Check for else
            for (size_t i = 0; i < node->child_count; i++) {
                if (node->children[i]->kind == NODE_ELSE) {
                    cg_puts(cg, " else {");
                    cg->indent_level++;
                    AstNode* else_node = node->children[i];
                    if (else_node->child_count > 0) {
                        if (else_node->children[0]->kind == NODE_BLOCK) {
                            cg->indent_level--;
                            cg_putc(cg, '\n');
                            emit_node(cg, else_node->children[0]);
                            cg->indent_level++;
                        } else {
                            cg_putc(cg, '\n');
                            emit_node(cg, else_node->children[0]);
                        }
                    }
                    cg->indent_level--;
                    emit_indent(cg);
                    cg_puts(cg, "}");
                }
            }
            break;
        }

        case NODE_WHILE: {
            emit_indent(cg);
            cg_puts(cg, "while (");
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 1) {
                if (node->children[1]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[1]);
                }
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "}");
            cg_putc(cg, '\n');
            break;
        }

        case NODE_FOR: {
            emit_indent(cg);
            cg_puts(cg, "for (");
            // Children: [0] = init, [1] = cond, [2] = inc, [3] = body
            if (node->child_count > 0 && node->children[0]) emit_node(cg, node->children[0]);
            cg_puts(cg, "; ");
            if (node->child_count > 1 && node->children[1]) emit_node(cg, node->children[1]);
            cg_puts(cg, "; ");
            if (node->child_count > 2 && node->children[2]) emit_node(cg, node->children[2]);
            cg_puts(cg, ") {");
            cg->indent_level++;
            if (node->child_count > 3 && node->children[3]) {
                if (node->children[3]->kind == NODE_BLOCK) {
                    cg->indent_level--;
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[3]);
                    cg->indent_level++;
                } else {
                    cg_putc(cg, '\n');
                    emit_node(cg, node->children[3]);
                }
            }
            cg->indent_level--;
            emit_indent(cg);
            cg_puts(cg, "}");
            cg_putc(cg, '\n');
            break;
        }

        case NODE_EXPR_STMT: {
            emit_indent(cg);
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            cg_puts(cg, ";\n");
            break;
        }

        case NODE_RETURN: {
            emit_indent(cg);
            cg_puts(cg, "return");
            if (node->child_count > 0 && node->children[0]) {
                cg_putc(cg, ' ');
                emit_node(cg, node->children[0]);
            }
            cg_puts(cg, ";\n");
            break;
        }

        case NODE_BREAK: {
            emit_indent(cg);
            cg_puts(cg, "break;\n");
            break;
        }

        case NODE_CONTINUE: {
            emit_indent(cg);
            cg_puts(cg, "continue;\n");
            break;
        }

        case NODE_DERIVATION: {
            // Emit derivation examples as comments
            for (size_t i = 0; i < node->child_count; i++) {
                AstNode* example = node->children[i];
                if (example->kind == NODE_DERIV_EXAMPLE) {
                    cg_puts(cg, "// Derivation example: ");
                    // Find the arrow position (last child is output)
                    size_t input_count = example->child_count > 0 ? example->child_count - 1 : 0;
                    for (size_t j = 0; j < input_count; j++) {
                        if (j > 0) cg_puts(cg, ", ");
                        // For literals, print value
                        if (example->children[j]->kind == NODE_LITERAL_INT) {
                            cg_printf(cg, "%" PRId64, example->children[j]->token.value.i64);
                        } else {
                            cg_puts(cg, "expr");
                        }
                    }
                    cg_puts(cg, " -> ");
                    if (input_count < example->child_count) {
                        AstNode* out = example->children[input_count];
                        if (out->kind == NODE_LITERAL_INT) {
                            cg_printf(cg, "%" PRId64, out->token.value.i64);
                        } else {
                            cg_puts(cg, "expr");
                        }
                    }
                    cg_putc(cg, '\n');
                }
            }
            break;
        }

        case NODE_BINARY_OP: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_printf(cg, " %s ", token_kind_name(node->token.kind));
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_UNARY_OP: {
            const char* op = token_kind_name(node->token.kind);
            if (node->token.kind == TOK_STAR) {
                cg_putc(cg, '*');
            } else if (node->token.kind == TOK_BIT_AND) {
                cg_putc(cg, '&');
            } else if (node->token.kind == TOK_INC || node->token.kind == TOK_DEC) {
                // Postfix: emit operand first
                if (node->child_count > 0) emit_node(cg, node->children[0]);
                cg_puts(cg, op);
                return;
            } else {
                cg_puts(cg, op);
            }
            if (node->child_count > 0) emit_node(cg, node->children[0]);
            break;
        }

        case NODE_TERNARY: {
            if (node->child_count >= 3) {
                emit_node(cg, node->children[0]);
                cg_puts(cg, " ? ");
                emit_node(cg, node->children[1]);
                cg_puts(cg, " : ");
                emit_node(cg, node->children[2]);
            }
            break;
        }

        case NODE_ASSIGN: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_printf(cg, " %s ", token_kind_name(node->token.kind));
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_CALL: {
            if (node->child_count > 0) {
                emit_node(cg, node->children[0]);
                cg_puts(cg, "(");
                for (size_t i = 1; i < node->child_count; i++) {
                    if (i > 1) cg_puts(cg, ", ");
                    emit_node(cg, node->children[i]);
                }
                cg_puts(cg, ")");
            }
            break;
        }

        case NODE_INDEX: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_putc(cg, '[');
                emit_node(cg, node->children[1]);
                cg_putc(cg, ']');
            }
            break;
        }

        case NODE_MEMBER: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_putc(cg, '.');
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_DEREF: {
            if (node->child_count >= 2) {
                emit_node(cg, node->children[0]);
                cg_puts(cg, "->");
                emit_node(cg, node->children[1]);
            }
            break;
        }

        case NODE_LITERAL_INT: {
            cg_printf(cg, "%" PRId64, node->token.value.i64);
            break;
        }

        case NODE_LITERAL_FLOAT: {
            cg_printf(cg, "%g", node->token.value.f64);
            break;
        }

        case NODE_LITERAL_STR: {
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            break;
        }

        case NODE_LITERAL_CHAR: {
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            break;
        }

        case NODE_VARIABLE: {
            // Variable reference (extract from token)
            cg_printf(cg, "%.*s", (int)node->token.len, node->token.text);
            break;
        }

        case NODE_PP_INCLUDE: {
            emit_indent(cg);
            cg_printf(cg, "%.*s\n", (int)node->token.len, node->token.text);
            break;
        }

        default:
            // Unknown node — skip silently
            break;
    }
}

// ── Output buffer helpers ───────────────────────────────────────────────

static void emit_indent(Codegen* cg) {
    for (int i = 0; i < cg->indent_level; i++) {
        cg_putc(cg, ' ');
        cg_putc(cg, ' ');
    }
}

static void cg_ensure_cap(Codegen* cg, size_t needed) {
    if (cg->output_cap == 0) {
        cg->output_cap = needed;
        cg->output = (char*)malloc(cg->output_cap);
        cg->output[0] = '\0';
    } else if (cg->output_len + needed >= cg->output_cap) {
        cg->output_cap *= 2;
        cg->output = (char*)realloc(cg->output, cg->output_cap);
    }
}

static void cg_putc(Codegen* cg, char c) {
    cg_ensure_cap(cg, 2);
    cg->output[cg->output_len++] = c;
    cg->output[cg->output_len] = '\0';
}

static void cg_puts(Codegen* cg, const char* s) {
    size_t len = strlen(s);
    cg_ensure_cap(cg, len + 1);
    memcpy(cg->output + cg->output_len, s, len);
    cg->output_len += len;
    cg->output[cg->output_len] = '\0';
}

static void cg_printf(Codegen* cg, const char* fmt, ...) {
    va_list args;
    va_start(args, fmt);
    int needed = vsnprintf(NULL, 0, fmt, args);
    va_end(args);
    if (needed < 0) return;

    cg_ensure_cap(cg, (size_t)needed + 1);
    va_start(args, fmt);
    vsnprintf(cg->output + cg->output_len, (size_t)needed + 1, fmt, args);
    va_end(args);
    cg->output_len += (size_t)needed;
}
